### ISSUE TITLE
Version Mismatch in Doclytics Logs

### ISSUE THREAD

**Issue by mikekaldig** [B-urb/doclytics#104]
I downloaded and integrated doclytics, pulling version 1.3.0 from GitHub. However, the logs show this version:

`doclytics_1  | Sep 24 19:05:06.803 INFO Application started, version: 1.1.4-rc.9
doclytics_1  | Sep 24 19:05:06.876 INFO Fetching custom fields from paperless at http://10.10.10.122:8777
doclytics_1  | Sep 24 19:05:06.901 INFO Fields: [Field { id: 2, name: "tagged", data_type: "boolean" }]
doclytics_1  | Sep 24 19:05:06.901 INFO Retrieve Documents from paperless at: http://10.10.10.122:8777, with query: NOT tagged=true
doclytics_1  | Sep 24 19:05:06.968 INFO Successfully retrieved 0 Documents
`

**Comment by mikekaldig** [comment]
And the tagging seems not work:

`doclytics_1  | Sep 24 19:10:22.674 INFO Creating field: date_received
doclytics_1  | Sep 24 19:10:22.707 ERRO Error creating custom field: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/)
doclytics_1  | Sep 24 19:10:22.707 ERRO Error: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/) creating custom field: date_received, skipping...
doclytics_1  | Sep 24 19:10:22.707 INFO Creating field: category
doclytics_1  | Sep 24 19:10:22.725 ERRO Error creating custom field: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/)
doclytics_1  | Sep 24 19:10:22.725 ERRO Error: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/) creating custom field: category, skipping...
doclytics_1  | Sep 24 19:10:22.725 INFO Creating field: topic
doclytics_1  | Sep 24 19:10:22.743 ERRO Error creating custom field: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/)
doclytics_1  | Sep 24 19:10:22.743 ERRO Error: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/) creating custom field: topic, skipping...
doclytics_1  | Sep 24 19:10:22.743 INFO Creating field: sender
doclytics_1  | Sep 24 19:10:22.761 ERRO Error creating custom field: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/)
doclytics_1  | Sep 24 19:10:22.761 ERRO Error: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/) creating custom field: sender, skipping...
doclytics_1  | Sep 24 19:10:22.761 INFO Creating field: recipient
doclytics_1  | Sep 24 19:10:22.778 ERRO Error creating custom field: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/)
doclytics_1  | Sep 24 19:10:22.778 ERRO Error: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/) creating custom field: recipient, skipping...
doclytics_1  | Sep 24 19:10:22.778 INFO Creating field: urgency
doclytics_1  | Sep 24 19:10:22.795 ERRO Error creating custom field: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/)
doclytics_1  | Sep 24 19:10:22.795 ERRO Error: HTTP status client error (400 Bad Request) for url (http://10.10.10.122:8777/api/custom_fields/) creating custom field: urgency, skipping...`

`version: '3.8'
services:
  doclytics:
  #image: bjoern5urban/doclytics:latest
   image: ghcr.io/b-urb/doclytics:v1.3.0-rc.10
   environment:
      PAPERLESS_BASE_URL: http://10.10.10.122:8777
      PAPERLESS_TOKEN: myToken
      OLLAMA_HOST: "10.10.10.251"
      OLLAMA_BASE_URL: "http://10.10.10.251:11434"
      OLLAMA_PORT: "11434"
      OLLAMA_SECURE_ENDPOINT: "false"
      OLLAMA_MODEL: "llama3.1:latest"
      MODE: "1"
      BASE_PROMPT: "Please extract metadata from the provided document and return it in JSON format.
                    The fields I need are
                    title,topic,sender,recipient,urgency(with value either n/a or low or medium or high),
                    date_received,category.
                    Analyze the document to find the values for these fields and format the response as a
                    JSON object. Use the most likely answer for each field.
                    The response should contain only JSON data where the key and values are all in simple string
                    format(no nested object) for direct parsing by another program. So now additional text or
                    explanation, no introtext, the answer should start and end with curly brackets
                    delimiting the json object"

   depends_on:
      - webserver
   volumes:
      - /share/Container/doclytics/data:/app/data

  redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - /share/Container/paperlessredis:/data

  db:
    image: postgres:14
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - /share/Container/paperlessdb:/var/lib/postgresql/data
environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperlessngx
    restart: unless-stopped
    privileged: true
    depends_on:
      - db
      - redis
      - gotenberg
      - tika
    ports:
      - 8777:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /share/Container/paperless/data:/usr/src/paperless/data
      - /share/Container/paperless/media:/usr/src/paperless/media
      - /share/Container/paperless/export:/usr/src/paperless/export
      - /share/Container/paperless/consume:/usr/src/paperless/consume
      - /share/Container/paperless/scripts:/usr/src/paperless/scripts
      - /share/Container/paperless/trash:/usr/src/paperless/trash
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1005
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_ADMIN_USER: username
      PAPERLESS_ADMIN_PASSWORD: password
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
      # PAPERLESS_CONSUMER_POLLING: 5
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TRASH_DIR: /tmp/
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_ENABLE_BARCODES: "true"
      PAPERLESS_CONSUMER_IGNORE_PATTERNS: '[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", ".@__thumb/*", "desktop.ini"]'
      LANGUAGE: "EN,DE"
      OLLAMA_HOST: "10.10.10.251"
      OLLAMA_BASE_URL: "http://10.10.10.251:11434"
      OLLAMA_PORT: "11434"
      OLLAMA_SECURE_ENDPOINT: "false"
      OLLAMA_MODEL: "llama3.1:latest"
      MODE: "1"
gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    container_name: gotenberg
    ports:
       - 3000:3000
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: tika
    ports:
      - 9998:9998
    restart: always
`

**Comment by B-urb** [comment]
This should be fixed with 2.0.0-rc.2.
