### ISSUE TITLE
Error at column 1

### ISSUE THREAD

**Issue by dannytsang** [B-urb/doclytics#33]
I'm trying to use bjoern5urban/doclytics:v1.0.1 in docker. I have set the PAPERLESS_BASE_URL and PAPERLESS_TOKEN but the container errors and stops.

The output I get is:
```
Error: Error("expected value", line: 2, column: 1)
Error at column 1: 
<!doctype html>
<html lang="en
```

any ideas?

**Comment by B-urb** [comment]
Can you provide anymore context? 
Which setup are you running paperless in ? 
Which format did you set the url in for Paperless and token?
Can you post the exact command you ran ?

**Comment by dannytsang** [comment]
I'm running this in Unraid.

Paperless is running as a container on port 8000 on the same docker network. Here are the parameters for doclytics:
![image](https://github.com/B-urb/doclytics/assets/567982/70c06846-e68e-4bed-9e8c-3e985a9f73bb)

The above should be equivalent to (i didn't list all the parameters):
```
docker run --name doclytics -e PAPERLESS_BASE_URL=http://paperless-ngx:8000 -e OLLAMA_HOST=ollama bjoern5urban/doclytics:v1.0.1
```

**Comment by B-urb** [comment]
Can you check which version of paperless you are running? With 1.17 on my system i was running into the same error. With paperless 2.7 which is my production instance it works fine, as long as you have custom fields defined.

**Comment by dannytsang** [comment]
I'm running 2.7.2.
![Screenshot_20240505-163057](https://github.com/B-urb/doclytics/assets/567982/0107e7ff-6cbb-4ba1-bbfd-b3931017f9ed)

Although you said custom fields... I don't have any so do I need to define those and with what 😅?

**Comment by B-urb** [comment]
Ah, I see, you need at least a custom field "tagged" of type boolean, which I use to check if a document has already been analyzed. Furthermore you need a custom_field for each property you want doclytics to set on the document. The name of the custom field has to corresond to the field in the query. You can see the example/example.prompt and [docs](https://github.com/B-urb/doclytics?tab=readme-ov-file#usage). For the field urgency from the example.prompt for example i have a corresponding custom field "urgency" of type text in paperless. if you create the field tagged and urgency, see if it works and let me know. I will expand the docs and create another issue to create the custom_fields on the fly in the next version.

**Comment by dannytsang** [comment]
I've created a boolean field called *tagged* and added it to 1 document and it still fails with the same error as above. Do I need to add the custom field to all my documents to clear the error?

**Comment by B-urb** [comment]
You shouldn't have to, that's weird. I have just released a new version v1.1.0, which probably does not fix the issue but should improve logging quite a bit. You can set env LOG_LEVEL to DEBUG for additional output. Maybe then we can pinpoint the error better.

**Comment by dannytsang** [comment]
```
Error: reqwest::Error { kind: Status(400), url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("paperless-ngx")), port: Some(8000), path: "/api/custom_fields/", query: None, fragment: None } }
Error: reqwest::Error { kind: Status(400), url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("paperless-ngx")), port: Some(8000), path: "/api/custom_fields/", query: None, fragment: None } }
May 06 08:10:15.426 INFO Application started !, version: 0.1.0
May 06 08:10:15.474 DEBG starting new connection: http://paperless-ngx:8000/, version: 0.1.0
May 06 08:10:15.474 DEBG resolving host="paperless-ngx", version: 0.1.0
May 06 08:10:15.475 DEBG connecting to 172.18.0.26:8000, version: 0.1.0
May 06 08:10:15.475 DEBG connected to 172.18.0.26:8000, version: 0.1.0
May 06 08:10:15.487 ERRO HTTP status client error (400 Bad Request) for url (http://paperless-ngx:8000/api/custom_fields/), version: 0.1.0
May 06 08:10:15.487 DEBG pooling idle connection for ("http", paperless-ngx:8000), version: 0.1.0
May 06 08:10:20.457 INFO Application started !, version: 0.1.0
May 06 08:10:20.507 DEBG starting new connection: http://paperless-ngx:8000/, version: 0.1.0
May 06 08:10:20.507 DEBG resolving host="paperless-ngx", version: 0.1.0
May 06 08:10:20.508 DEBG connecting to 172.18.0.26:8000, version: 0.1.0
May 06 08:10:20.508 DEBG connected to 172.18.0.26:8000, version: 0.1.0
May 06 08:10:20.519 ERRO HTTP status client error (400 Bad Request) for url (http://paperless-ngx:8000/api/custom_fields/), version: 0.1.0
May 06 08:10:20.519 DEBG pooling idle connection for ("http", paperless-ngx:8000), version: 0.1.0
```

**Comment by B-urb** [comment]
it normally works with the fully qualified url e.g. http://paperless-ngx:8000. Works for me in that format. The bad request error seems like the connectivity is there, but paperless does not like the request. Do you get any logs in the paperless webserver itself ? The debug logs are not written to console in paperless but to the log file.

**Comment by dannytsang** [comment]
OMG, I'm such an idiot. It was indeed Paperless complaining my docker host was not in the allowed list. I added paperless-ngx to **PAPERLESS_ALLOWED_HOSTS** and hey presto it's connected.

I do get another error but I will raise it as a new issue. Thanks @B-urb !
