### ISSUE TITLE
Create Custom fields automatically when returned by llm

### ISSUE THREAD

**Issue by B-urb** [B-urb/doclytics#34]
As in #33 there seems to be an error, when custom fields are not set. 

- [x] Create custom fields on startup/on the fly when using doclytics
- [x] expand documentation

**Comment by tural-ali** [comment]
Hi @B-urb . Not sure how can I enable this feature?

**Comment by B-urb** [comment]
Right now, you would have to build the docker image from the feature/automatically-create-customfields branch. I will complete this feature soon and then it will be available from the registry as a release candidate.

**Comment by B-urb** [comment]
@tural-ali the latest rc version includes an early working version of this. You just have to set the Mode environment variable to 1
