### ISSUE TITLE
Autotagging

### ISSUE THREAD

**Issue by tural-ali** [B-urb/doclytics#47]
Hello,
1. can we use Doclytics for automatically tagging, creating new tags if they don't exist?

2. is it possible to fill not only custom but also Paperless's in-built fields?

3. I use LLAMA3-7B. Is it optimal or better to use some other model?

Many thanks for your effort.

**Comment by B-urb** [comment]
Hi, 

1. for this there is the #34 which I hopefully can work on in the near future. I have some free time next week and will maybe get around to working on this.
2. This by now is only done for the title but I will try to work something out to make this possible. Good idea.
3. This is the one I use and I feel like it gives the best results for that model size, I will probably make llama3 the default model in the near future. 

Thanks for your good suggestions!

**Comment by tural-ali** [comment]
thank you for your efforts @B-urb

**Comment by B-urb** [comment]
I am going to close this in favor of #34. You can track the progress there. I already started implementing already.

**Comment by tural-ali** [comment]
Hi @B-urb When I said tags, I didn't mean to create new custom fields but to add actual tags 
![Screenshot by Dropbox Capture](https://github.com/B-urb/doclytics/assets/724507/8114940f-be6d-4b9f-be46-2b83fafa1307)
