### ISSUE TITLE
Also fill paperless default fields

### ISSUE THREAD

**Issue by B-urb** [B-urb/doclytics#49]
As suggested by @tural-ali in #47 , doclytics should also fill all other default fields of paperless documents.

**Comment by JigSawFr** [comment]
Agree that FR is a must have !

**Comment by B-urb** [comment]
I am thinking about how to tackle this, since paperless does have its own matching algorithm for correspondent, tags and document types. I would rather do this the better way and build up on that in a way that uses manually created entries first and create new ones if matching can't be done.

**Comment by joestump** [comment]
@B-urb I was just thinking about this when I came here to see if someone had requested it. I was envisioning basically pulling correspondents and tags into the prompt – maybe as a template? Correspondents require IDs too so embed JSON in the prompt? I have a bunch of Correspondents already, so this method would work well for me.

**Comment by B-urb** [comment]
Yes, thats the approach, I am currently working on. This should be the way to go. The only tbd point is when to create new tags and correspondents and how to design the prompt to incorporate that.

**Comment by B-urb** [comment]
I am able to generate tag and add them to documents, but the generation is stil a bit flaky: 
![Screenshot 2024-10-05 at 10 09 19](https://github.com/user-attachments/assets/0786d36d-a4b5-4084-ae9a-85907eb181fb)

In general however the state looks good.

**Comment by B-urb** [comment]
The feature for filling the default fields is now available in 2.0.0-rc.1. Please be careful as it contains a breaking change regarding the configuration. See the [Release Notes](https://github.com/B-urb/doclytics/releases/tag/v2.0.0-rc.1) for more info.
