### ISSUE TITLE
"storage_path" API value type

### ISSUE THREAD

**Issue by swarnat** [B-urb/doclytics#51]
Hy,

At first: This is exactly the project I was looking for. 👍Thanks for managing this.
I implemented LLM with ollama in our company and think about some weeks ago, what else can be done. 
Because the understand of these models is almost much better, then I expected.

I only have one issue, which is not related to LLM, but the Paperless API implementation. I'm not fully sure, why this works for you. 😄 
The API for me returns the storage_path value as type "u32" not "string". 
It only works, after I changed the Document struct to use storage_path of type "Option<u32>"

And when I look in the docs, then it looks like, it is correct: [https://docs.paperless-ngx.com/api/#file-uploads](https://docs.paperless-ngx.com/api/#file-uploads)

Thanks!

**Comment by B-urb** [comment]
I think you are right. The implementation I did was based on assumptions of the type. I personally don't have storage path set so I think I never noticed. This seems to be a bug. Thanks for reporting 👍
