### ISSUE TITLE
Load more than 25 documents

### ISSUE THREAD

**Issue by madman2012** [B-urb/doclytics#55]
How do you get it to load more than 25 documents in a batch? It seems to process that and then shuts down.  Any way to tell it to process x number?

Still getting errors paring json response from LLM 

Jun 11 18:46:06.877 ERRO Error parsing llm response json expected `,` or `}` at line 6 column 18
Jun 11 18:46:48.638 ERRO Error parsing llm response json key must be a string at line 4 column 1
Jun 11 18:48:41.691 ERRO Error parsing llm response json key must be a string at line 7 column 32

bjoern5urban/doclytics:v1.2.0-rc.1

**Comment by B-urb** [comment]
Hi @madman2012, sorry for the late response. Can you elaborate on the problem a bit ? Does the whole application run never process more than 25 documents ?

**Comment by madman2012** [comment]
Hi thanks for coming back.  It’s it only requests and processes 25 documents then shuts down.

________________________________

**Comment by B-urb** [comment]
Thanks for pointing this out, indeed paperless itself seems to have a pagination with a limit of 25. This stems from the underlying django api framework which is why(unfortunately) it is not documented withing paperless itself. I created a fix and will try to merge it asap.
