### ISSUE TITLE
FR: Publish docker images/tags on Github

### ISSUE THREAD

**Issue by JigSawFr** [B-urb/doclytics#56]
Hi there !
Thanks for this wonderful app !
Can you also publish docker images to Github ? (ghcr.io).
So we can avoid using dockerhub,
Thanks !

**Comment by JigSawFr** [comment]
@B-urb thanks but think that you missed to set the visibility of package to public 💯 (we don't see it, most of time due it's due to wrong initial permissions)
Have a nice day !

**Comment by B-urb** [comment]
The pipeline didn't go through since github requires lowercase reponames, yet does not provide to lower case variabales in actions. I will fix this with static name for now.
