### ISSUE TITLE
Docker deployment & instruction

### ISSUE THREAD

**Issue by ytzelf** [B-urb/doclytics#9]
Hi,
This looks like a really interesting project; would it be possible to build a docker image for it?
Thank you very much !

**Comment by B-urb** [comment]
I added a first working version of a docker container and some docs: [a063715](https://github.com/B-urb/doclytics/commit/a063715a45282a996874c5f0b6b235ceaf3844bb)

**Comment by codingstube** [comment]
Hi Björn,
thanks for this cool implementation.
On my setup the docker container restarts always after the processing was finished. I changed the Dockerfile that a shell script is executed and loop the execution of doclytics:

start.sh:
#!/bin/bash

while true; do
  # Ruf das Programm auf
  /usr/doclytics/target/release/./doclytics

  # Warte 10 Sekunden
  #sleep 10
  sleep $SLEEP_TIME
done

Dockerfile:

FROM rust:1.79

ENV HTTPS_PROXY=http://m240wg.nettetal.krzn.de:3128/

WORKDIR /usr/doclytics
COPY . .

RUN cargo install --path .

#CMD ["doclytics"]
CMD ["/usr/doclytics/start.sh"]
