### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tural-ali** [B-urb/doclytics#93]
Hi @B-urb,
thank you for your efforts to make organized people's life a bit easier. 
I love the idea in general, would like to make it more useful. 
Currently, even when Doclytics processes documents, there is a certain manual work needs to be done on each document. The most routine things are, that IMHO could be easily done using LLMs:
 - Tagging
 - Selecting correct correspondent and/or creating it
TBH, all other custom tags are not making much difference in contrast to the ones I mentioned. 
Would love to see improvements in before-mentioned directions, in your next iterations.

**Comment by B-urb** [comment]
Hi @tural-ali, thanks for taking the time of giving feedback. I agree that tagging is a much needed feature. I already started development but had too little time in the last weeks. I will probably have a bit more time in the upcoming weeks. So will try to get this feature ready in the near future.

**Comment by B-urb** [comment]
Just to give a quick update on this. I am  almost done with the implementation and hope I will have a RC by the end of next week.

**Comment by B-urb** [comment]
The feature for filling the default fields is now available in 2.0.0-rc.1. Please be careful as it contains a breaking change regarding the configuration. See the [Release Notes](https://github.com/B-urb/doclytics/releases/tag/v2.0.0-rc.1) for more info.
